# Generated by Django 5.0.6 on 2024-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='default.png', upload_to='thumbnails')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
